### ISSUE TITLE
Adding tasks to a project with a prefix of "id" fails

### ISSUE THREAD

**Issue by lgrz** [GothenburgBitFactory/taskwarrior#2069]
taskwarrior version:

```
$ task --version
2.5.1
```

Adding a task to a project "idea" fails:

```
$ task add foo bar proj:idea
The expression could not be evaluated.
```

Add a task to any project with a prefix "id" fails:

```
$ task add foo bar proj:id123
The expression could not be evaluated.
```

Adding a task to the project "id" succeeds:

```
$ task add foo bar proj:id
Created task 131.
The project 'id' has changed.  Project 'id' is 0% complete (1 task remaining).
```

Adding a task to the project "i" succeeds:

```
$ task add foo bar proj:i
Created task 132.
The project 'i' has changed.  Project 'i' is 0% complete (1 task remaining).
```

I would expect all the above cases to succeed. It seems that `id` is parsed
specially by the command line syntax.

Just to be sure I tried this on an empty database:

```
$ task
[task next]
No matches.
$ task add hell world proj:idea
The expression could not be evaluated.
$ task add hell world proj:id
Created task 1.
The project 'id' has changed.  Project 'id' is 0% complete (1 task remaining).
```

A related issue is that when performing bulk changes to the project named "id"
will place each task in a project named as the task id:

```
$ task proj:idea modify proj:id
  - Project will be changed from 'idea' to '21'.
Modify task 21 'foo bop zang'? (yes/no/all/quit) y
Modifying task 21 'foo bop zang'.

  - Project will be changed from 'idea' to '27'.
Modify task 27 'foo bar baz'? (yes/no/all/quit) q
```

I would expect the bulk changes to place all tasks in the project named "id"
rather than assign each task a project named as the task id.

Task diagnostics:

```
task 2.5.1
   Platform: Linux

Compiler
    Version: 6.3.0 20170221
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      CMake: 3.7.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.8
 Build type: None

Configuration
       File: /home/foo/.taskrc (found), 1198 bytes, mode 100644
       Data: /home/foo/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $EDITOR: vim
     Server: 
      Trust: strict
Certificate: , not readable, 0 bytes
        Key: , not readable, 0 bytes
    Ciphers: NORMAL
      Creds: 

Hooks
     System: Enabled
   Location: /home/foo/.task/hooks
             (-none-)

Tests
      $TERM: xterm-256color (151x72)
       Dups: Scanned 255 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 255 tasks for broken references:
             No broken references found

```

**Comment by austb** [comment]
Confirmed this bug on Mac OSX as well.

Projects named `i` and `id` both work
```
$ task add foo bar project:i
Sync successful.  1 changes uploaded.
Created task 27.
The project 'i' has changed.  Project 'i' is 0% complete (1 task remaining).
$ task add foo bar project:id
Sync successful.  1 changes uploaded.
Created task 28.
The project 'id' has changed.  Project 'id' is 0% complete (1 task remaining).
```
But `id` followed by a character or characters fails.
```
$ task add foo bar project:ids
The expression could not be evaluated.
```
or
```
$ task add foo bar project:idea
The expression could not be evaluated.
```

```
$ task diagnostics


task 2.5.1
   Platform: Darwin

Compiler
    Version: 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)
       Caps: +stdc +stdc_hosted +LP64 +c8 +i32 +l64 +vp64 +time_t64
 Compliance: C++11

Build Features
      Built: Sep 18 2017 12:51:06
      CMake: 3.9.2
    libuuid: libuuid + uuid_unparse_lower
  libgnutls: 3.5.15
 Build type: Release

Configuration
       File: /Users/austin.blatt/.taskrc (found), 2179 bytes, mode 100644
       Data: /Users/austin.blatt/.task (found), dir, mode 40755
    Locking: Enabled
         GC: Enabled
    $VISUAL: vim
     Server: sync.austinblatt.com:53589
         CA: ~/.task/austinblatt.ca.pem, readable, 3147 bytes
      Trust: ignore hostname
Certificate: ~/.task/austinblatt.cert.pem, readable, 3173 bytes
        Key: ~/.task/austinblatt.key.pem, readable, 20322 bytes
    Ciphers: NORMAL
      Creds: Private/Austin Blatt/************************************

Hooks
     System: Enabled
   Location: /Users/austin.blatt/.task/hooks
     Active: on-exit.sync          (executable) (symlink)
             on-modify.timewarrior (executable) (symlink)
   Inactive:

Tests
      $TERM: screen-256color (265x52)
       Dups: Scanned 124 tasks for duplicate UUIDs:
             No duplicates found
 Broken ref: Scanned 124 tasks for broken references:
             No broken references found
```

**Comment by pbeckingham** [comment]
Known issue, should be fixed in 2.5.2.

**Comment by tbabej** [comment]
Closing as duplicate of #1826

**Comment by b0o** [comment]
@tbabej The issue you references as a duplicate has been closed for over a year, yet this bug still seems to be present in v2.5.1. Can we re-open this?

**Comment by tbabej** [comment]
@b0o That's because, unfortunately, 2.5.2 has not been released for a year now.

**Comment by tbabej** [comment]
For the record, this fix was released as part of 2.5.2 in December of 2020.
