### ISSUE TITLE
Core dump when modifying a task containing single quote

### ISSUE THREAD

**Issue by unseen-traveller** [GothenburgBitFactory/taskwarrior#2704]
Running task-2.5.3-2.fc35 on Fedora Linux 35 (Workstation Edition).

* What command(s) did you run?
Command was probably something like:
task 99 modify "***** REPLY TO LORIE'S EMAIL, URGENTLY *****"
Double quotes to stop globbing.

* What did you expect to happen?
Change task name.

* What actually happened?
Crashed. "/usr/include/c++/11/bits/basic_string.h:1039: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
Aborted (core dumped)"

* Paste the output of the ```task diag``` command.
I can't. Taskwarrior crashes with above message each time I run it.

Last two lines of backlog.data are:
{"description":"REPLY TO LORIE'S EMAIL, URGENTLY","entry":"...","modified":"...","priority":"H","project":"flat","status":"pending", ...}
{"description":"****** REPLY TO LORIE\\
ie, single quote seems to have caused crash, resulting in incomplete JSON file.

The last three lines in undo.data are:
time ...
old [description:"REPLY TO LORIE'S EMAIL, URGENTLY" entry:"..." modified:"..." priority:"H" project:"..." status:"pending" ...]
new [description:"****** REPLY TO LORIE\\---

The other files are ok.
Will delete broken lines to see if that fixes things.

**Comment by yashlala** [comment]
I can't reproduce this issue with TaskWarrior 2.6.1. 

```
$ task add 'yee'
Created task 16
$ task 16 modify "***** REPLY TO LORIE'S EMAIL, URGENTLY *****"
Modifying task 16 '***** REPLY TO LORIE'S EMAIL, URGENTLY *****'.
Modified 1 task.
```

Might be a Fedora specific issue (or fixed in the newer versions)?

**Comment by tbabej** [comment]
:slightly_smiling_face: Indeed, I believe this was fixed in 2.6. The relevant issue should be #2189

**Comment by unseen-traveller** [comment]
Deleting the corrupted lines in backlog.data and undo.data didn't make any difference; taskwarrior still crashes. Dunno why. Will have to edit data files into taskwarrior commands and reload all tasks, from scratch, as a bash script.
Also, building 2.6.1 from source didn't work. I installed all listed dependencies (including libuuid), but cmake command gives me "libuuid not found". Probably an easy fix, but all-in-all, taskwarrior hasn't given me the user experience I was looking for. :)
Will move on to another app.

**Comment by tbabej** [comment]
@unseen-traveller With respect to installing the dependencies, I suspect you might have installed the dependency (the `libuuid` package), but not the devel package (which contains the source code). This is unfortunately the tricky thing to keep in mind when building C/C++ code bases with packaged deps. On Fedora, the sources would be shipped as the `libuuid-devel` package. After installing that, cmake should have no problem locating it.
